# Generated by Django 4.0.6 on 2022-08-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdQuestoes', models.IntegerField()),
                ('qtdAlternativas', models.IntegerField()),
                ('gabaritoPadrao', models.CharField(max_length=200)),
                ('dtProva', models.DateField()),
                ('idProcessoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_1', to='app.processo')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=100)),
                ('respostas', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('etnia', models.CharField(max_length=200)),
                ('pcd', models.BooleanField(default=False)),
                ('idProcessoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_0', to='app.processo')),
                ('provaFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prova', to='app.prova')),
            ],
        ),
    ]
